### ISSUE TITLE
Méthode __repr__

### ISSUE THREAD

**Issue by deladan** [flotpython/course#18]
Bonjour,

J'ai une question par rapport à l'exercice fifo en w3-s8, concernant ce fil de discussion sur le forum :
https://www.fun-mooc.fr/courses/course-v1:UCA+107001+session02/discussion/forum/3b1ccba01dd306b009ba4571e6a53220320e792b/threads/5dee60d0a0241e4b84019f15
Ne demande-t-il pas l'implémentation de la méthode spéciale `__repr__` ?
Or, cette méthode n'est pas introduite dans la vidéo d'introduction aux classes.

Isa

**Comment by parmentelat** [comment]
Bonjour Isabelle

Merci d'avoir signalé ça, en effet il y a souci ! J'ai répondu à l'étudiant dans le fil.

Je vais voir si je peux m'en sortir en tripotant `nbautoeval`, à suivre sur
https://github.com/parmentelat/nbautoeval/issues/9
