### ISSUE TITLE
Fichier players.py

### ISSUE THREAD

**Issue by mycaule** [flotpython/course#19]
Bonjour,

Dans ce notebook il y a un lien vers le fichier `players.py` , mais le lien est cassé.
https://github.com/flotpython/course/blob/master/w8/w8-s8-c1-players.ipynb

Merci d'avance et bravo pour votre super cours.

**Comment by parmentelat** [comment]
bonjour

est-ce que vous pouvez être plus précis sur l'emplacement du lien cassé ?

si avec chrome je vais sur FUN, dans le notebook en question je vois ceci :

![image](https://user-images.githubusercontent.com/4519227/75145437-3c7ea680-56f9-11ea-86f8-3c4675a1132e.png)

mais ça ne doit pas être ce que vous indiquez puisque si je clique sur ce lien cela m'ouvre dans un autre onglet un notebook : 
![image](https://user-images.githubusercontent.com/4519227/75145548-6cc64500-56f9-11ea-952f-7ce68cc77470.png)

alors effectivement, par le passé lorsqu'on cliquait ça provoquait directement le download du code Python, alors que maintenant on passe par un notebook intermédiaire et il faut utiliser le menu 'download as Python''
...

***

pour info ce nouveau comportement n'était pas exactement volontaire dans ce cas précis, il est dû à l'utilisation de plus en plus généralisée que je fais de `jupytext`; ainsi les fichiers 'plain Python' peuvent à présent être ouverts comme des notebooks.

**Comment by mycaule** [comment]
J'ai fini par trouver le fichier grâce au fuzzy finder de GitHub.

La particularité est que j'ai suivi votre cours de manière accélérée sans passer par les videos et sans passer par les liens de la plateforme FUN.

Dans le fichier PDF compilant les 9 semaines de cours que j'ai récupéré sur la page d'accueil, il faut savoir que les liens hypertextes ne fonctionnent pas.

J'ai ensuite essayé de retrouvé les sources sur GitHub et je suis tombé sur [`w8-s8-c1-players.ipynb`](https://github.com/flotpython/course/blob/master/w8/w8-s8-c1-players.ipynb)

Quand on regarde les sources, et qu'on clique depuis GitHub,
```html
<a href="data/players.py">Voyez ici le code de `players.py`</a>
```
pointe vers https://render.githubusercontent.com/view/data/players.py
tandis que le fichier se trouve en réalité sur https://github.com/flotpython/course/blob/master/data/players.py

**Comment by parmentelat** [comment]
effectivement nos objectifs c'est principalement que l'on puisse explorer le contenu depuis un dépôt git cloné, que ce soit sur la plateforme de notebooks qui héberge les notebooks derrière fun-mooc, ou localement pour les étudiants qui ont installé jupyter

nous n'en sommes pas encore à faire tourner ces contenus directement sur colab, ce qui serait je vous l'accorde sans doute plus simple à certains égards, mais ça n'existait pas quand on a mis en ligne pour la première fois en 2014, et du coup maintenant on a pris nos habitudes ...
