### ISSUE TITLE
souci d'orthographe dans un quiz

### ISSUE THREAD

**Issue by deladan** [flotpython/course#6]
Bonjour Thierry,

Je ne sais pas si c'est vraiment le lieu pour signaler cette broutille, mais il persiste une petite erreur d'orthographe dans un des quiz du mooc.
w3-s6-q1-exceptions : dans l'explication de la réponse à la question 1, il est dit que :

> Il existe également des exceptions (comme StopIteration) qui sont automatiquement capturée

Il faudrait ajouter un s à capturée.
Ce qui est étrange, c'est que cette correction a été faite sur le fichier dans github, dans les deux repositories.
Isa

**Comment by parmentelat** [comment]
> On 17 Apr 2019, at 04:54, Isabelle Poirier <notifications@github.com> wrote:
> 
> Bonjour Thierry,
> 
> Je ne sais pas si c'est vraiment le lieu pour signaler cette broutille, mais il persiste une petite erreur d'orthographe dans un des quiz du mooc.
> w3-s6-q1-exceptions : dans l'explication de la réponse à la question 1, il est dit que :
> 
> Il existe également des exceptions (comme StopIteration) qui sont automatiquement capturée
> 
> Il faudrait ajouter un s à capturée.
> Ce qui est étrange, c'est que cette correction a été faite sur le fichier dans github, dans les deux repositories.
> Isa
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Bonjour Isabelle

les quiz ne sont pas traités comme les notebooks,
il ne suffit pas de mettre à jour github (pourquoi d’ailleurs tu dis *deux* repositories ?)
il faut aussi les changer à la main dans l’edx sur fun-mooc

je viens de le faire pour ce quiz-là, merci de l’avoir signalé 

Un grand merci à toi par ailleurs pour ta présence et tes réponses pertinentes dans le forum :)

— Thierry

**Comment by deladan** [comment]
Je parlais du repository qui a été archivé https://github.com/parmentelat/flotpython

Mais je ne comprends peut-être encore pas tout à github ;-)

**Comment by parmentelat** [comment]
tu peux oublier le vieux repo, il a été archivé, on ne peut plus écrire dedans, et il n'est plus utilisé nulle part (j'espère en tous cas)
