### ISSUE TITLE
W4-S3-X2 - la fonction taxes n'est pas continue

### ISSUE THREAD

**Issue by aollier** [flotpython/course#64]
Bonjour Thierry,

La fonction taxes n'est pas continue pour deux raisons :

- Le type du paramètre d'entrée est entier. Il y a donc déjà discontinuité.
- Le résultat est plutôt en escalier, même si avec beaucoup de recul cela ressemble à des segments.
Exemples :
taxes(12500) = 0
taxes(12501) = 0
taxes(12502) = 0
taxes(12503) = 0
taxes(12504) = 0
taxes(12505) = 1
taxes(12506) = 1
taxes(12507) = 1

Par conséquent, je pense qu'il faut supprimer la phrase 

> évidemment on parle ici d'une fonction continue

**Comment by parmentelat** [comment]
bonjour Adrien

au sens strict mathématique, bien sûr non tu as raison elle n'est pas continue

dans le sens commun par contre, cette indication est là pour faire réfléchir les - souvent - jeunes gens qui n'ont jamais été exposés à ce barême, car en première analyse ils pensent souvent - à tort bien sûr - que le calcul se fait en appliquant à tout le revenu un taux qui dépend de la tranche

donc je n'ai pas de problème à reformuler, mais ça me semble important de conserver cet indice, que si le barême était calculé comme ci-dessus, il ne serait pas continu - au sens commun du terme - et il y aurait là quelque chose de très injuste, et que donc il faut réfléchir un peu plus

peut-être un angle serait d'insérer une image statique de la courbe - comme ça on verra que la courbe est continue sans avoir à l'écrire ?

**Comment by aollier** [comment]
corrigé par 472efba
