### ISSUE TITLE
launchbinder run python 3.7

### ISSUE THREAD

**Issue by Karduin** [flotpython/course#67]
Launch binder run python 3.7. Peut-être configurer pour du 3.10 afin d'être en phase avec le cours ?

**Comment by parmentelat** [comment]
good idea

from what I can see here
https://mybinder.readthedocs.io/en/latest/using/config_files.html#runtime-txt-specifying-runtimes
and here
https://github.com/binder-examples/requirements
it looks like it's just a matter of creating a `runtime.txt`

I'll give this a try right away
